package org.usfirst.frc5124.WestTorranceSwagbotics2016.subsystems;

import org.usfirst.frc5124.WestTorranceSwagbotics2016.Robot;
import org.usfirst.frc5124.WestTorranceSwagbotics2016.RobotMap;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Catapult extends Subsystem {

    public static boolean catapultIsDown = true;
    private final DoubleSolenoid catapultSolenoid1 = RobotMap.catapultCatapultSolenoid1;
    private final DoubleSolenoid catapultSolenoid2 = RobotMap.catapultCatapultSolenoid2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void load() {
    	if(Robot.intake.isDown()) {
    		catapultSolenoid1.set(Value.kReverse);
    		catapultSolenoid2.set(Value.kReverse);
    	}
    }
    
    public void fire(){
    	if(Robot.intake.isDown()) {
    		catapultSolenoid1.set(Value.kForward);
        	catapultSolenoid2.set(Value.kForward);
        	
    	}
    	
    }
    
    public void setCatapultBooleanDown() {
    	catapultIsDown = true;
    }
    
    public void setCatapultBooleanUp() {
    	catapultIsDown = false;
    }
    
    public boolean isDown() {
    	return catapultIsDown;
    }
    
    
}

